name: TorPrivoxy Docker Build

on:
  schedule:
    - cron: '12 2 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMG_NAME: ghcr.io/disaac/torprivoxy
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup qemu
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: define bdate
        run: echo "BDATE=$(date +%d-%m-%Y)" >> $GITHUB_ENV
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMG_NAME }}
          tags: |
            type=raw,value=${{ env.BDATE }},enable=true
      - name: Docker metadata Debian
        id: metadata-debian
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMG_NAME }}
          tags: |
            type=raw,value=${{ env.BDATE }},enable=true,suffix="-debian",suffixLatest=true
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm/v6,linux/arm64
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push debian
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm/v6,linux/arm64
          tags: ${{ steps.metadata-debian.outputs.tags }}
          labels: ${{ steps.metadata-debian.outputs.labels }}
          file: Dockerfile.debian
          cache-from: type=gha
          cache-to: type=gha,mode=max
